import pygame
from ui_class.constants import BTN_COLOR
from display_constants import SIDE_MENU_RECT_ACTIVE

BOARD_WIDTH = 800
BOARD_HEIGHT = 800

BOARD_THEME_W = 700
BOARD_THEME_H = 720

SCOREBOARD_WIDTH = SIDE_MENU_RECT_ACTIVE.w//1.35
SCOREBOARD_HEIGHT = SIDE_MENU_RECT_ACTIVE.h//2
SCOREBOARD_COLOR = BTN_COLOR
SCOREBOARD_ALPHA = 180

ROWS, COLS = 8, 8
SQUARE_SIZE = BOARD_WIDTH//COLS

OFFSET = 0 # 33
BOARD_OFFSET = 0  #58

PLAYER_ONE = "Blue"
PLAYER_TWO = "Orange"

# --------- Colors --------- 
# Main Palette
OAR_BLUE = '#627E9B'
DARK_GRAY_BLUE = '#2C455E'
DARK_JUNGLE_BLUE = '#0E2129'
PERSIMMON_ORANGE = '#FF7045'
BURNT_UMBER = '#91301D'
WHITE = '#FFFFFF'

BG_COLOR = ('#627E9B') # lighter shade of blue
DARK_ORANGE = '#902F1C'
DARK_BLUE = '#193C55'

IMAGINARY_WHITE = '#FEFEFE'
# Basic
RED = '#F93535'
DARKER_RED = '#6D1919'
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GRAY = (128, 128, 128)
BROWN = '#A05B08'
LIGHT_BLUE = '#3B6DFE'
DARKER_BLUE = '#182D69'
YELLOW = '#FFFF5B'
LIME = '#9BCB48'


# BOARD_W = BOARD_BLACK.get_width()
# BOARD_H = BOARD_BLACK.get_height()
