# Dictionary

mode = "mode"
symbolAdd = "symbolAdd"
symbolSubtract = "symbolSubtract"
symbolMultiply = "symbolMultiply"
symbolDivide = "symbolDivide"
symbolRandom = "symbolRandom"
piece_values = "piece_values"
allowPromotion = "allowPromotion"
allowCapture = "allowCapture"
allowChainCapture = "allowChainCapture"
allowMandatoryCapture = "allowMandatoryCapture"
enableTimer = "enableTimer"
timer_turn = "timer_turn"
timer_global = "timer_global"
allowActions = "allowActions"
allowCheats = "allowCheats"
ai = "ai"